Basic data structures and algorihms in C++: cesar::CesarCypherImpl Class Reference
cesar::CesarCypherImpl Class Reference
Public Member Functions
CesarCypherImpl (std::size_t shift) noexcept
Initialize the shift that this CesarCypher applies.
std::string cypher (const std::string &sentence)
Apply Caesar cypher to sentence and return result as a new string.
std::string decypher (const std::string &sentence)
Apply reverse Caesar cypher to sentence and return result as a new string.
void cypher (const std::string &sentence, char *output)
Apply Caesar cypher to sentence and write result in buffer.
void decypher (const std::string &sentence, char *output)
Apply reverse Caesar cypher to sentence and write result in buffer.
Private Member Functions
std::string cypher (const std::string &sentence, std::size_t shift)
void cypher (const std::string &sentence, char *buffer, std::size_t shift)
Private Attributes
std::size_t shift_
const std::size_t zero_ = 'a'
const std::size_t range_ = 'z' - 'a' + 1
Friends
class CesarCypher
Detailed Description
Definition at line 12 of file pimpl.cpp.
Constructor & Destructor Documentation
CesarCypherImpl()
cesar::CesarCypherImpl::CesarCypherImpl (std::size_t shift) inline noexcept
Initialize the shift that this CesarCypher applies.
Parameters
shift How much to shift each character
Definition at line 19 of file pimpl.cpp.
References range_, and shift_.
{
     shift_ = shift % range_;
   }
Member Function Documentation
cypher() [1/4]
std::string cesar::CesarCypherImpl::cypher (const std::string & sentence) inline
Apply Caesar cypher to sentence and return result as a new string.
Parameters
sentence The sentence to cypher
Returns
The cyphered sentence
Definition at line 28 of file pimpl.cpp.
References shift_.
Referenced by cypher(), and decypher().
{
     return cypher(sentence, shift_);
   }
cypher() [2/4]
void cesar::CesarCypherImpl::cypher (const std::string & sentence, char * output) inline
Apply Caesar cypher to sentence and write result in buffer.
Parameters
sentence The sentence to cypher
output The output buffer. It must have size > sentence.size()
Definition at line 47 of file pimpl.cpp.
References cypher(), and shift_.
{
     cypher(sentence, output, shift_);
   }
cypher() [3/4]
std::string cesar::CesarCypherImpl::cypher (const std::string & sentence, std::size_t shift) inline private
Definition at line 67 of file pimpl.cpp.
References cypher().
{
     if (shift == 0) {
       return sentence;
     }
     char output[sentence.size() + 1];
     output[sentence.size()] = '\0';
     cypher(sentence, output, shift);
     return output;
   }
cypher() [4/4]
void cesar::CesarCypherImpl::cypher (const std::string & sentence, char * buffer, std::size_t shift) inline private
Definition at line 86 of file pimpl.cpp.
References range_, and zero_.
{
     // No shift, just copy sentence on buffer
     if (shift == 0) {
       std::memcpy(buffer, sentence.c_str(), sentence.size());
       return;
     }
     auto idx = 0U;
     for (const char& ch : sentence) {
       const std::size_t candidate_value = ch + shift;
       if (candidate_value >= range_ + zero_) {
         buffer[idx++] = zero_ + (candidate_value - zero_) % range_;
       } else {
         buffer[idx++] = candidate_value;
       }
     }
   }
decypher() [1/2]
std::string cesar::CesarCypherImpl::decypher (const std::string & sentence) inline
Apply reverse Caesar cypher to sentence and return result as a new string.
Parameters
sentence The sentence to decypher
Returns
The decyphered sentence
Definition at line 38 of file pimpl.cpp.
References cypher(), range_, and shift_.
{
     return cypher(sentence, range_ - shift_);
   }
decypher() [2/2]
void cesar::CesarCypherImpl::decypher (const std::string & sentence, char * output) inline
Apply reverse Caesar cypher to sentence and write result in buffer.
Parameters
sentence The sentence to decypher
output The output buffer. It must have size > sentence.size()
Definition at line 56 of file pimpl.cpp.
References cypher(), range_, and shift_.
{
     return cypher(sentence, output, range_ - shift_);
   }
Friends And Related Function Documentation
CesarCypher
friend class CesarCypher friend
Definition at line 61 of file pimpl.cpp.
Field Documentation
range_
const std::size_t cesar::CesarCypherImpl::range_ = 'z' - 'a' + 1 private
Definition at line 108 of file pimpl.cpp.
Referenced by CesarCypherImpl(), cypher(), and decypher().
shift_
std::size_t cesar::CesarCypherImpl::shift_ private
Definition at line 106 of file pimpl.cpp.
Referenced by CesarCypherImpl(), cypher(), and decypher().
zero_
const std::size_t cesar::CesarCypherImpl::zero_ = 'a' private
Definition at line 107 of file pimpl.cpp.
Referenced by cypher().
The documentation for this class was generated from the following file:
pimpl/pimpl.cpp