Basic data structures and algorihms in C++: cesar::CesarCypher Class Reference
cesar::CesarCypher Class Reference
#include <cesar.hpp>
Public Member Functions
CesarCypher (std::size_t shift) noexcept
Initialize the shift that this CesarCypher applies.
std::string cypher (const std::string &sentence)
Apply Caesar cypher to sentence and return result as a new string.
std::string decypher (const std::string &sentence)
Apply reverse Caesar cypher to sentence and return result as a new string.
void cypher (const std::string &sentence, char *output)
Apply Caesar cypher to sentence and write result in buffer.
void decypher (const std::string &sentence, char *output)
Apply reverse Caesar cypher to sentence and write result in buffer.
CesarCypher (std::size_t shift) noexcept
Initialize the shift that this CesarCypher applies.
~CesarCypher () noexcept
For std::unique_ptr to work with incomplete types this destructor needs to be declared after the CesarCypherImpl class is defined. See Modern Effective C++, unique_ptr.
CesarCypher (const CesarCypher &other)
Copy constructor.
const CesarCypher & operator= (const CesarCypher &other)
Assignment operator.
std::string cypher (const std::string &sentence)
Apply Caesar cypher to sentence and return result as a new string.
std::string decypher (const std::string &sentence)
Apply reverse Caesar cypher to sentence and return result as a new string.
void cypher (const std::string &sentence, char *output)
Apply Caesar cypher to sentence and write result in buffer.
void decypher (const std::string &sentence, char *output)
Apply reverse Caesar cypher to sentence and write result in buffer.
Private Member Functions
std::string cypher (const std::string &sentence, std::size_t shift)
void cypher (const std::string &sentence, char *buffer, std::size_t shift)
Private Attributes
std::size_t shift_
const std::size_t zero_ = 'a'
const std::size_t range_ = 'z' - 'a' + 1
std::unique_ptr< CesarCypherImpl > impl_
Detailed Description
Definition at line 12 of file cesar.hpp.
Constructor & Destructor Documentation
CesarCypher() [1/3]
cesar::CesarCypher::CesarCypher (std::size_t shift) noexcept
Initialize the shift that this CesarCypher applies.
Parameters
shift How much to shift each character
Definition at line 9 of file cesar.cpp.
{
   shift_ = shift % range_;
 }
CesarCypher() [2/3]
cesar::CesarCypher::CesarCypher (std::size_t shift) noexcept
Initialize the shift that this CesarCypher applies.
Parameters
shift How much to shift each character
~CesarCypher()
cesar::CesarCypher::~CesarCypher () default noexcept
For std::unique_ptr to work with incomplete types this destructor needs to be declared after the CesarCypherImpl class is defined. See Modern Effective C++, unique_ptr.
CesarCypher() [3/3]
cesar::CesarCypher::CesarCypher (const CesarCypher & other)
Copy constructor.
Definition at line 123 of file pimpl.cpp.
References impl_.
{
   impl_ = std::make_unique<CesarCypherImpl>(other.impl_->shift_);
 }
Member Function Documentation
cypher() [1/6]
std::string cesar::CesarCypher::cypher (const std::string & sentence)
Apply Caesar cypher to sentence and return result as a new string.
Parameters
sentence The sentence to cypher
Returns
The cyphered sentence
Definition at line 58 of file cesar.cpp.
References shift_.
Referenced by cypher(), decypher(), and operator=().
{
   return cypher(sentence, shift_);
 }
cypher() [2/6]
std::string cesar::CesarCypher::cypher (const std::string & sentence)
Apply Caesar cypher to sentence and return result as a new string.
Parameters
sentence The sentence to cypher
Returns
The cyphered sentence
cypher() [3/6]
void cesar::CesarCypher::cypher (const std::string & sentence, char * output)
Apply Caesar cypher to sentence and write result in buffer.
Parameters
sentence The sentence to cypher
output The output buffer. It must have size > sentence.size()
Definition at line 66 of file cesar.cpp.
References cypher(), and shift_.
{
   cypher(sentence, output, shift_);
 }
cypher() [4/6]
std::string cesar::CesarCypher::cypher (const std::string & sentence, std::size_t shift) inline private
Definition at line 46 of file cesar.cpp.
References cypher().
{
   if (shift == 0) {
     return sentence;
   }
   char output[sentence.size() + 1];
   output[sentence.size()] = '\0';
   cypher(sentence, output, shift);
   return output;
 }
cypher() [5/6]
void cesar::CesarCypher::cypher (const std::string & sentence, char * buffer, std::size_t shift) inline private
Definition at line 21 of file cesar.cpp.
References range_, and zero_.
{
   // No shift, just copy sentence on buffer
   if (shift == 0) {
     std::memcpy(buffer, sentence.c_str(), sentence.size());
     return;
   }
   auto idx = 0U;
   for (const char& ch : sentence) {
     const std::size_t candidate_value = ch + shift;
     if (candidate_value >= range_ + zero_) {
       buffer[idx++] = zero_ + (candidate_value - zero_) % range_;
     } else {
       buffer[idx++] = candidate_value;
     }
   }
 }
cypher() [6/6]
void cesar::CesarCypher::cypher (const std::string & sentence, char * output)
Apply Caesar cypher to sentence and write result in buffer.
Parameters
sentence The sentence to cypher
output The output buffer. It must have size > sentence.size()
decypher() [1/4]
std::string cesar::CesarCypher::decypher (const std::string & sentence)
Apply reverse Caesar cypher to sentence and return result as a new string.
Parameters
sentence The sentence to decypher
Returns
The decyphered sentence
Definition at line 62 of file cesar.cpp.
References cypher(), range_, and shift_.
Referenced by operator=().
{
   return cypher(sentence, range_ - shift_);
 }
decypher() [2/4]
void cesar::CesarCypher::decypher (const std::string & sentence, char * output)
Apply reverse Caesar cypher to sentence and write result in buffer.
Parameters
sentence The sentence to decypher
output The output buffer. It must have size > sentence.size()
Definition at line 70 of file cesar.cpp.
References cypher(), range_, and shift_.
{
   return cypher(sentence, output, range_ - shift_);
 }
decypher() [3/4]
std::string cesar::CesarCypher::decypher (const std::string & sentence)
Apply reverse Caesar cypher to sentence and return result as a new string.
Parameters
sentence The sentence to decypher
Returns
The decyphered sentence
decypher() [4/4]
void cesar::CesarCypher::decypher (const std::string & sentence, char * output)
Apply reverse Caesar cypher to sentence and write result in buffer.
Parameters
sentence The sentence to decypher
output The output buffer. It must have size > sentence.size()
operator=()
const CesarCypher & cesar::CesarCypher::operator= (const CesarCypher & other)
Assignment operator.
Definition at line 127 of file pimpl.cpp.
References cypher(), decypher(), impl_, and shift_.
{
   this->impl_->shift_ = other.impl_->shift_;
   return *this;
 }
Field Documentation
impl_
std::unique_ptr<CesarCypherImpl> cesar::CesarCypher::impl_ private
Definition at line 66 of file pimpl.hpp.
Referenced by CesarCypher(), and operator=().
range_
const std::size_t cesar::CesarCypher::range_ = 'z' - 'a' + 1 private
Definition at line 56 of file cesar.hpp.
Referenced by cypher(), and decypher().
shift_
std::size_t cesar::CesarCypher::shift_ private
Definition at line 54 of file cesar.hpp.
Referenced by cypher(), decypher(), and operator=().
zero_
const std::size_t cesar::CesarCypher::zero_ = 'a' private
Definition at line 55 of file cesar.hpp.
Referenced by cypher().
The documentation for this class was generated from the following files:
cesar_cypher/cesar.hpp
pimpl/pimpl.hpp
cesar_cypher/cesar.cpp
pimpl/pimpl.cpp